# -*- coding: utf-8 -*-
"""Easy_OCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wRprNY4vH5RORCVONR5sHmJ4nKLjY8oZ
"""

pip install torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

"""Pytorch installed"""

pip install torchvision

pip install git+git://github.com/jaidedai/easyocr.git

import easyocr

"""# Customized the api model"""

reader = easyocr.Reader(["en","fr"], gpu = True)

import PIL ##image lib

from PIL import ImageDraw

im = PIL.Image.open("french.png")
im

text = reader.readtext("french.png")
text

for i in text:
  print(i[1])
##Need to update to facilitate proper document to text conversation.
##next task : to make the text to word conversion of output, then making it in proper way for documents
