# -*- coding: utf-8 -*-
"""Easy_OCR_with_saving_file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x8QZzgYThTwa0L7VwUn_15k_BHTP1AzX
"""

pip install torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

"""Pytorch installed"""

pip install torchvision

pip install git+git://github.com/jaidedai/easyocr.git

import easyocr

"""# Customized the api model"""

reader = easyocr.Reader(["en","fr"], gpu = True)

import PIL ##image lib

from PIL import ImageDraw

im = PIL.Image.open("french.png")
im

from google.colab import drive
drive.mount('/content/drive')

text = reader.readtext("french.png")
text

l = []
for i in text:
  print(i[1])
  l.append(i[1])

import pickle

pickle_output_file = open("data.txt","wb")
pickle.dump(l,pickle_output_file)
pickle_output_file.close()

pickle_output_file2 = open("data2.txt","wb")
for i in text:
  print(i[1])
  pickle.dump(i[1],pickle_output_file2)
pickle_output_file2.close()